[package]
name = "pilf_buddy_alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.10"
pi_pointer = { git = "https://github.com/AsyncModules/pi_pointer.git", version = "0.1.2" }
crate_interface = "0.1"
